name: GitHub Metrics

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Header — name, joined, followers, repos
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shrotriya-lalit
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          config_padding: 6%, 10%

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shrotriya-lalit
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, less
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_categories: markup, programming
          config_timezone: Asia/Kolkata

      - name: Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shrotriya-lalit
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kolkata

      - name: Fortune
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/fortune.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shrotriya-lalit
          base: ""
          plugin_fortune: yes
          config_timezone: Asia/Kolkata
